name: Terraform Apply

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ "develop" ]
      
env:
    TERRAFORM_DIR: infras/
    AWS_REGION: "us-east-2"
    AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_DIR }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.8'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      #- name: Terraform destroy
      #  run: terraform destroy -auto-approve


      - name: Output Instance Public IP
        run: echo "Instance IP:$(terraform output instance_ip)"

      - name: Output Postgres Connection String
        run: echo "Connection String:postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@$(terraform output postgres_ip)/${{ secrets.POSTGRES_DATABASE }}"
